server:
    port: 9000
spring:
    application:
        name: user-service




eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: client
        instance-id: ${spring.application.name}:${vcap.applicationinstance_id:${psring.application.instance_id:${random.value}}}
