server:
    port: 9000
spring:
    application:
        name: @pom.artifactId@




eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: user-service
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
