eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=name,baidu
        - id: zhihu_route
          uri: https://www.zhihu.com/
          predicates:
            - Query=name,zhihu

management:
  endpoints:
    web:
      exposure:
        include: '*'

  security:
    enabled: false