server:
  port: 8000



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}



test:
  enable: true


spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_learning?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  application:
    name: shiro-service
mybatis:
  typeAliasesPackage: com.dhw.shirodemo1.model.domain
  mapperLocations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.yml
